"""Contains all the data models used in inputs/outputs"""

from .dal_enums_taxation_system_aqsi_enum import DALEnumsTaxationSystemAqsiEnum
from .nebular_api_controllers_v3_documents_acceptance_create_acceptance_document_request_position_v3 import (
    NebularApiControllersV3DocumentsAcceptanceCreateAcceptanceDocumentRequestPositionV3,
)
from .nebular_api_controllers_v3_documents_acceptance_create_acceptance_document_request_v3 import (
    NebularApiControllersV3DocumentsAcceptanceCreateAcceptanceDocumentRequestV3,
)
from .nebular_api_controllers_v3_documents_acceptance_get_acceptance_document_positions_response_row_v3 import (
    NebularApiControllersV3DocumentsAcceptanceGetAcceptanceDocumentPositionsResponseRowV3,
)
from .nebular_api_controllers_v3_documents_acceptance_get_acceptance_document_positions_response_v3 import (
    NebularApiControllersV3DocumentsAcceptanceGetAcceptanceDocumentPositionsResponseV3,
)
from .nebular_api_controllers_v3_documents_acceptance_get_acceptance_document_response_v3 import (
    NebularApiControllersV3DocumentsAcceptanceGetAcceptanceDocumentResponseV3,
)
from .nebular_api_controllers_v3_documents_app_list_documents_response_v3 import (
    NebularApiControllersV3DocumentsAppListDocumentsResponseV3,
)
from .nebular_api_controllers_v3_documents_app_list_documents_row_v3 import (
    NebularApiControllersV3DocumentsAppListDocumentsRowV3,
)
from .nebular_api_controllers_v3_documents_inventory_create_inventory_document_request_position_v3 import (
    NebularApiControllersV3DocumentsInventoryCreateInventoryDocumentRequestPositionV3,
)
from .nebular_api_controllers_v3_documents_inventory_create_inventory_document_request_v3 import (
    NebularApiControllersV3DocumentsInventoryCreateInventoryDocumentRequestV3,
)
from .nebular_api_controllers_v3_documents_inventory_get_inventory_document_positions_response_row_v3 import (
    NebularApiControllersV3DocumentsInventoryGetInventoryDocumentPositionsResponseRowV3,
)
from .nebular_api_controllers_v3_documents_inventory_get_inventory_document_positions_response_v3 import (
    NebularApiControllersV3DocumentsInventoryGetInventoryDocumentPositionsResponseV3,
)
from .nebular_api_controllers_v3_documents_inventory_get_inventory_document_response_v3 import (
    NebularApiControllersV3DocumentsInventoryGetInventoryDocumentResponseV3,
)
from .nebular_api_controllers_v3_documents_management_create_management_document_request_position_v3 import (
    NebularApiControllersV3DocumentsManagementCreateManagementDocumentRequestPositionV3,
)
from .nebular_api_controllers_v3_documents_management_create_management_document_request_v3 import (
    NebularApiControllersV3DocumentsManagementCreateManagementDocumentRequestV3,
)
from .nebular_api_controllers_v3_documents_management_get_management_document_positions_response_row_v3 import (
    NebularApiControllersV3DocumentsManagementGetManagementDocumentPositionsResponseRowV3,
)
from .nebular_api_controllers_v3_documents_management_get_management_document_positions_response_v3 import (
    NebularApiControllersV3DocumentsManagementGetManagementDocumentPositionsResponseV3,
)
from .nebular_api_controllers_v3_documents_management_get_management_document_response_v3 import (
    NebularApiControllersV3DocumentsManagementGetManagementDocumentResponseV3,
)
from .nebular_api_controllers_v3_documents_movement_create_movement_document_request_v3 import (
    NebularApiControllersV3DocumentsMovementCreateMovementDocumentRequestV3,
)
from .nebular_api_controllers_v3_documents_movement_get_movement_document_positions_response_row_v3 import (
    NebularApiControllersV3DocumentsMovementGetMovementDocumentPositionsResponseRowV3,
)
from .nebular_api_controllers_v3_documents_movement_get_movement_document_positions_response_v3 import (
    NebularApiControllersV3DocumentsMovementGetMovementDocumentPositionsResponseV3,
)
from .nebular_api_controllers_v3_documents_movement_get_movement_document_response_v3 import (
    NebularApiControllersV3DocumentsMovementGetMovementDocumentResponseV3,
)
from .nebular_api_controllers_v3_documents_production_create_production_document_request_position_v3 import (
    NebularApiControllersV3DocumentsProductionCreateProductionDocumentRequestPositionV3,
)
from .nebular_api_controllers_v3_documents_production_create_production_document_request_v3 import (
    NebularApiControllersV3DocumentsProductionCreateProductionDocumentRequestV3,
)
from .nebular_api_controllers_v3_documents_production_get_production_document_positions_response_row_v3 import (
    NebularApiControllersV3DocumentsProductionGetProductionDocumentPositionsResponseRowV3,
)
from .nebular_api_controllers_v3_documents_production_get_production_document_positions_response_v3 import (
    NebularApiControllersV3DocumentsProductionGetProductionDocumentPositionsResponseV3,
)
from .nebular_api_controllers_v3_documents_production_get_production_document_response_v3 import (
    NebularApiControllersV3DocumentsProductionGetProductionDocumentResponseV3,
)
from .nebular_api_controllers_v3_documents_write_off_create_write_off_document_request_position_v3 import (
    NebularApiControllersV3DocumentsWriteOffCreateWriteOffDocumentRequestPositionV3,
)
from .nebular_api_controllers_v3_documents_write_off_create_write_off_document_request_v3 import (
    NebularApiControllersV3DocumentsWriteOffCreateWriteOffDocumentRequestV3,
)
from .nebular_api_controllers_v3_documents_write_off_get_write_off_document_positions_response_row_v3 import (
    NebularApiControllersV3DocumentsWriteOffGetWriteOffDocumentPositionsResponseRowV3,
)
from .nebular_api_controllers_v3_documents_write_off_get_write_off_document_positions_response_v3 import (
    NebularApiControllersV3DocumentsWriteOffGetWriteOffDocumentPositionsResponseV3,
)
from .nebular_api_controllers_v3_documents_write_off_get_write_off_document_response_v3 import (
    NebularApiControllersV3DocumentsWriteOffGetWriteOffDocumentResponseV3,
)
from .nebular_api_dtos_common_order_dto import NebularApiDtosCommonOrderDto
from .nebular_api_dtos_get_order_status_with_receipts_content import NebularApiDtosGetOrderStatusWithReceiptsContent
from .nebular_api_dtos_good_category_dto_v2 import NebularApiDtosGoodCategoryDtoV2
from .nebular_api_enums_adding_type_enum import NebularApiEnumsAddingTypeEnum
from .nebular_api_enums_agent_type_enum import NebularApiEnumsAgentTypeEnum
from .nebular_api_enums_cashless_payments_enum import NebularApiEnumsCashlessPaymentsEnum
from .nebular_api_enums_device_payment_type_enum import NebularApiEnumsDevicePaymentTypeEnum
from .nebular_api_enums_doc_type_enum import NebularApiEnumsDocTypeEnum
from .nebular_api_enums_electronic_check_enum import NebularApiEnumsElectronicCheckEnum
from .nebular_api_enums_fiscalization_status_enum import NebularApiEnumsFiscalizationStatusEnum
from .nebular_api_enums_input_method_enum import NebularApiEnumsInputMethodEnum
from .nebular_api_enums_marking_type_enum import NebularApiEnumsMarkingTypeEnum
from .nebular_api_enums_no_return_enum import NebularApiEnumsNoReturnEnum
from .nebular_api_enums_payment_method_type_enum import NebularApiEnumsPaymentMethodTypeEnum
from .nebular_api_enums_payment_subject_type_enum import NebularApiEnumsPaymentSubjectTypeEnum
from .nebular_api_enums_taxation_system_in_orders_enum import NebularApiEnumsTaxationSystemInOrdersEnum
from .nebular_api_enums_unit_code_enum import NebularApiEnumsUnitCodeEnum
from .nebular_api_enums_vat_rate_enum import NebularApiEnumsVATRateEnum
from .nebular_api_models_common_api_acquiring_data_v3 import NebularApiModelsCommonApiAcquiringDataV3
from .nebular_api_models_common_api_cash_mode_sums import NebularApiModelsCommonApiCashModeSums
from .nebular_api_models_common_api_cheque import NebularApiModelsCommonApiCheque
from .nebular_api_models_common_api_credit import NebularApiModelsCommonApiCredit
from .nebular_api_models_common_api_customer_info import NebularApiModelsCommonApiCustomerInfo
from .nebular_api_models_common_api_date_time_model import NebularApiModelsCommonApiDateTimeModel
from .nebular_api_models_common_api_debit import NebularApiModelsCommonApiDebit
from .nebular_api_models_common_api_error_model import NebularApiModelsCommonApiErrorModel
from .nebular_api_models_common_api_guid_model import NebularApiModelsCommonApiGuidModel
from .nebular_api_models_common_api_industry_attribute import NebularApiModelsCommonApiIndustryAttribute
from .nebular_api_models_common_api_money import NebularApiModelsCommonApiMoney
from .nebular_api_models_common_api_operational_attribute import NebularApiModelsCommonApiOperationalAttribute
from .nebular_api_models_common_api_order_dto_content import NebularApiModelsCommonApiOrderDtoContent
from .nebular_api_models_common_api_order_dto_extended_content import NebularApiModelsCommonApiOrderDtoExtendedContent
from .nebular_api_models_common_api_order_dto_extended_position import NebularApiModelsCommonApiOrderDtoExtendedPosition
from .nebular_api_models_common_api_order_dto_position import NebularApiModelsCommonApiOrderDtoPosition
from .nebular_api_models_common_api_qr_pay_transaction import NebularApiModelsCommonApiQrPayTransaction
from .nebular_api_models_common_api_reconciliations import NebularApiModelsCommonApiReconciliations
from .nebular_api_models_common_api_spasibo import NebularApiModelsCommonApiSpasibo
from .nebular_api_models_common_api_taxes import NebularApiModelsCommonApiTaxes
from .nebular_api_models_common_api_с_ounters import NebularApiModelsCommonApiСOunters
from .nebular_api_models_integrations_additional_user_attribute import (
    NebularApiModelsIntegrationsAdditionalUserAttribute,
)
from .nebular_api_models_integrations_agent_info import NebularApiModelsIntegrationsAgentInfo
from .nebular_api_models_integrations_check_close_v3 import NebularApiModelsIntegrationsCheckCloseV3
from .nebular_api_models_integrations_order_check_close import NebularApiModelsIntegrationsOrderCheckClose
from .nebular_api_models_integrations_supplier_info import NebularApiModelsIntegrationsSupplierInfo
from .nebular_api_models_lk_service_address import NebularApiModelsLkServiceAddress
from .nebular_api_models_lk_service_base_shop import NebularApiModelsLkServiceBaseShop
from .nebular_api_models_lk_service_bind_device_to_account_model import (
    NebularApiModelsLkServiceBindDeviceToAccountModel,
)
from .nebular_api_models_lk_service_binding_response import NebularApiModelsLkServiceBindingResponse
from .nebular_api_models_lk_service_cashiers_v2_cashier_device import NebularApiModelsLkServiceCashiersV2CashierDevice
from .nebular_api_models_lk_service_cashiers_v2_create_cashier_response_v2 import (
    NebularApiModelsLkServiceCashiersV2CreateCashierResponseV2,
)
from .nebular_api_models_lk_service_cashiers_v2_get_cashier_response_v2 import (
    NebularApiModelsLkServiceCashiersV2GetCashierResponseV2,
)
from .nebular_api_models_lk_service_client import NebularApiModelsLkServiceClient
from .nebular_api_models_lk_service_client_extended_v2 import NebularApiModelsLkServiceClientExtendedV2
from .nebular_api_models_lk_service_client_v2 import NebularApiModelsLkServiceClientV2
from .nebular_api_models_lk_service_custom_property import NebularApiModelsLkServiceCustomProperty
from .nebular_api_models_lk_service_device_list import NebularApiModelsLkServiceDeviceList
from .nebular_api_models_lk_service_device_model import NebularApiModelsLkServiceDeviceModel
from .nebular_api_models_lk_service_extended_good_v2 import NebularApiModelsLkServiceExtendedGoodV2
from .nebular_api_models_lk_service_get_goods_category import NebularApiModelsLkServiceGetGoodsCategory
from .nebular_api_models_lk_service_get_goods_category_v2 import NebularApiModelsLkServiceGetGoodsCategoryV2
from .nebular_api_models_lk_service_get_receipt_cashier import NebularApiModelsLkServiceGetReceiptCashier
from .nebular_api_models_lk_service_get_shop_v2 import NebularApiModelsLkServiceGetShopV2
from .nebular_api_models_lk_service_goods_extended_good_dto_v2 import NebularApiModelsLkServiceGoodsExtendedGoodDtoV2
from .nebular_api_models_lk_service_goods_rows_2_system_string_system_private_core_lib_version_6000_cultureneutral_public_key_token_7_cec_85d7_bea_7798e_system_string_system_private_core_lib_version_6000_cultureneutral_public_key_token_7_cec_85d7_bea_7798e import (
    NebularApiModelsLkServiceGoodsRows2SystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7Cec85D7Bea7798ESystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7Cec85D7Bea7798E,
)
from .nebular_api_models_lk_service_goods_shop_info import NebularApiModelsLkServiceGoodsShopInfo
from .nebular_api_models_lk_service_goods_v2_set_prices import NebularApiModelsLkServiceGoodsV2SetPrices
from .nebular_api_models_lk_service_group import NebularApiModelsLkServiceGroup
from .nebular_api_models_lk_service_id_response_v2 import NebularApiModelsLkServiceIdResponseV2
from .nebular_api_models_lk_service_img import NebularApiModelsLkServiceImg
from .nebular_api_models_lk_service_lk_shift import NebularApiModelsLkServiceLkShift
from .nebular_api_models_lk_service_lk_slip import NebularApiModelsLkServiceLkSlip
from .nebular_api_models_lk_service_loyalty_card import NebularApiModelsLkServiceLoyaltyCard
from .nebular_api_models_lk_service_modifier_good import NebularApiModelsLkServiceModifierGood
from .nebular_api_models_lk_service_modifier_option import NebularApiModelsLkServiceModifierOption
from .nebular_api_models_lk_service_orders_v2_orders_response import NebularApiModelsLkServiceOrdersV2OrdersResponse
from .nebular_api_models_lk_service_orders_v2_post_order_v2 import NebularApiModelsLkServiceOrdersV2PostOrderV2
from .nebular_api_models_lk_service_post_cashier import NebularApiModelsLkServicePostCashier
from .nebular_api_models_lk_service_post_shop_v2 import NebularApiModelsLkServicePostShopV2
from .nebular_api_models_lk_service_receipt_properties import NebularApiModelsLkServiceReceiptProperties
from .nebular_api_models_lk_service_receipt_type_enum import NebularApiModelsLkServiceReceiptTypeEnum
from .nebular_api_models_lk_service_receipts_v2_client_info import NebularApiModelsLkServiceReceiptsV2ClientInfo
from .nebular_api_models_lk_service_receipts_v2_loyalty_content import NebularApiModelsLkServiceReceiptsV2LoyaltyContent
from .nebular_api_models_lk_service_receipts_v2_receipts_response_v2 import (
    NebularApiModelsLkServiceReceiptsV2ReceiptsResponseV2,
)
from .nebular_api_models_lk_service_receipts_v2_row import NebularApiModelsLkServiceReceiptsV2Row
from .nebular_api_models_lk_service_row_2_system_string_system_private_core_lib_version_6000_cultureneutral_public_key_token_7_cec_85d7_bea_7798e_system_string_system_private_core_lib_version_6000_cultureneutral_public_key_token_7_cec_85d7_bea_7798e import (
    NebularApiModelsLkServiceRow2SystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7Cec85D7Bea7798ESystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7Cec85D7Bea7798E,
)
from .nebular_api_models_lk_service_shop_data import NebularApiModelsLkServiceShopData
from .nebular_api_models_lk_service_shops_shop_v2_set_prices import NebularApiModelsLkServiceShopsShopV2SetPrices
from .nebular_api_models_lk_service_slot_info import NebularApiModelsLkServiceSlotInfo
from .nebular_api_models_lk_service_sorting import NebularApiModelsLkServiceSorting
from .nebular_api_models_lk_service_v3_contractors_v3_contractors_sorted_v3 import (
    NebularApiModelsLkServiceV3ContractorsV3ContractorsSortedV3,
)
from .nebular_api_models_lk_service_v3_contractors_v3_create_contractor_request_v3 import (
    NebularApiModelsLkServiceV3ContractorsV3CreateContractorRequestV3,
)
from .nebular_api_models_lk_service_v3_contractors_v3_create_contractor_response_v3 import (
    NebularApiModelsLkServiceV3ContractorsV3CreateContractorResponseV3,
)
from .nebular_api_models_lk_service_v3_contractors_v3_get_contractor_response_v3 import (
    NebularApiModelsLkServiceV3ContractorsV3GetContractorResponseV3,
)
from .nebular_api_models_lk_service_v3_contractors_v3_list_contractors_response_v3 import (
    NebularApiModelsLkServiceV3ContractorsV3ListContractorsResponseV3,
)
from .nebular_api_models_lk_service_v3_contractors_v3_list_contractors_row_v3 import (
    NebularApiModelsLkServiceV3ContractorsV3ListContractorsRowV3,
)
from .nebular_api_models_lk_service_v3_contractors_v3_update_contractor_request_v3 import (
    NebularApiModelsLkServiceV3ContractorsV3UpdateContractorRequestV3,
)
from .nebular_api_models_lk_service_v3_devices_v3_bind_device_to_account_model_v3 import (
    NebularApiModelsLkServiceV3DevicesV3BindDeviceToAccountModelV3,
)
from .nebular_api_models_lk_service_v3_devices_v3_bind_device_to_account_model_v3_cashier import (
    NebularApiModelsLkServiceV3DevicesV3BindDeviceToAccountModelV3Cashier,
)
from .nebular_api_models_lk_service_v3_devices_v3_bind_device_to_account_model_v3_shop import (
    NebularApiModelsLkServiceV3DevicesV3BindDeviceToAccountModelV3Shop,
)
from .nebular_api_models_lk_service_v3_devices_v3_device_setting_v3 import (
    NebularApiModelsLkServiceV3DevicesV3DeviceSettingV3,
)
from .nebular_api_models_lk_service_v3_devices_v3_device_settings_profile_v3 import (
    NebularApiModelsLkServiceV3DevicesV3DeviceSettingsProfileV3,
)
from .nebular_api_models_lk_service_v3_devices_v3_devices_sorted_v3 import (
    NebularApiModelsLkServiceV3DevicesV3DevicesSortedV3,
)
from .nebular_api_models_lk_service_v3_devices_v3_devices_v3_custom_property import (
    NebularApiModelsLkServiceV3DevicesV3DevicesV3CustomProperty,
)
from .nebular_api_models_lk_service_v3_devices_v3_devices_v3_shop import (
    NebularApiModelsLkServiceV3DevicesV3DevicesV3Shop,
)
from .nebular_api_models_lk_service_v3_devices_v3_get_device_response_v3 import (
    NebularApiModelsLkServiceV3DevicesV3GetDeviceResponseV3,
)
from .nebular_api_models_lk_service_v3_devices_v3_list_devices_response_v3 import (
    NebularApiModelsLkServiceV3DevicesV3ListDevicesResponseV3,
)
from .nebular_api_models_lk_service_v3_devices_v3_list_devices_row_v3 import (
    NebularApiModelsLkServiceV3DevicesV3ListDevicesRowV3,
)
from .nebular_api_models_lk_service_v3_documents_v3_create_document_related_entity_v3 import (
    NebularApiModelsLkServiceV3DocumentsV3CreateDocumentRelatedEntityV3,
)
from .nebular_api_models_lk_service_v3_documents_v3_create_document_request_position_v3 import (
    NebularApiModelsLkServiceV3DocumentsV3CreateDocumentRequestPositionV3,
)
from .nebular_api_models_lk_service_v3_documents_v3_create_document_response_v3 import (
    NebularApiModelsLkServiceV3DocumentsV3CreateDocumentResponseV3,
)
from .nebular_api_models_lk_service_v3_documents_v3_document_positions_response_row_good_v3 import (
    NebularApiModelsLkServiceV3DocumentsV3DocumentPositionsResponseRowGoodV3,
)
from .nebular_api_models_lk_service_v3_documents_v3_documents_sorted_v3 import (
    NebularApiModelsLkServiceV3DocumentsV3DocumentsSortedV3,
)
from .nebular_api_models_lk_service_v3_documents_v3_get_document_related_entity_v3 import (
    NebularApiModelsLkServiceV3DocumentsV3GetDocumentRelatedEntityV3,
)
from .nebular_api_models_lk_service_v3_error_model_v3 import NebularApiModelsLkServiceV3ErrorModelV3
from .nebular_api_models_lk_service_v3_error_v3 import NebularApiModelsLkServiceV3ErrorV3
from .nebular_api_models_lk_service_warehouse_v2_warehouse_get_shop_v2 import (
    NebularApiModelsLkServiceWarehouseV2WarehouseGetShopV2,
)
from .nebular_api_models_receipt_models_base_client_info import NebularApiModelsReceiptModelsBaseClientInfo
from .nebular_api_models_receipt_models_base_loyalty_content import NebularApiModelsReceiptModelsBaseLoyaltyContent
from .nebular_api_models_receipt_models_lk_rows_1_nebular_api_models_lk_service_lk_shift_nebular_api_version_1000_cultureneutral_public_key_tokennull import (
    NebularApiModelsReceiptModelsLkRows1NebularApiModelsLkServiceLkShiftNebularApiVersion1000CultureneutralPublicKeyTokennull,
)
from .nebular_api_models_receipt_models_lk_rows_1_nebular_api_models_lk_service_lk_slip_nebular_api_version_1000_cultureneutral_public_key_tokennull import (
    NebularApiModelsReceiptModelsLkRows1NebularApiModelsLkServiceLkSlipNebularApiVersion1000CultureneutralPublicKeyTokennull,
)
from .nebular_api_models_receipt_models_loyalty import NebularApiModelsReceiptModelsLoyalty
from .nebular_api_models_receipt_models_modifier_option_pointer import (
    NebularApiModelsReceiptModelsModifierOptionPointer,
)
from .nebular_api_models_receipt_models_payment_v3 import NebularApiModelsReceiptModelsPaymentV3
from .nebular_api_models_receipt_models_receipt_content_v3 import NebularApiModelsReceiptModelsReceiptContentV3
from .nebular_api_models_receipt_models_receipt_position_v32 import NebularApiModelsReceiptModelsReceiptPositionV32
from .nebular_api_models_receipt_models_receipt_v3 import NebularApiModelsReceiptModelsReceiptV3
from .post_v2_list_goods_body import PostV2ListGoodsBody
from .post_v2_list_goods_categories_body import PostV2ListGoodsCategoriesBody
from .post_v2_shops_prices_body import PostV2ShopsPricesBody

__all__ = (
    "DALEnumsTaxationSystemAqsiEnum",
    "NebularApiControllersV3DocumentsAcceptanceCreateAcceptanceDocumentRequestPositionV3",
    "NebularApiControllersV3DocumentsAcceptanceCreateAcceptanceDocumentRequestV3",
    "NebularApiControllersV3DocumentsAcceptanceGetAcceptanceDocumentPositionsResponseRowV3",
    "NebularApiControllersV3DocumentsAcceptanceGetAcceptanceDocumentPositionsResponseV3",
    "NebularApiControllersV3DocumentsAcceptanceGetAcceptanceDocumentResponseV3",
    "NebularApiControllersV3DocumentsAppListDocumentsResponseV3",
    "NebularApiControllersV3DocumentsAppListDocumentsRowV3",
    "NebularApiControllersV3DocumentsInventoryCreateInventoryDocumentRequestPositionV3",
    "NebularApiControllersV3DocumentsInventoryCreateInventoryDocumentRequestV3",
    "NebularApiControllersV3DocumentsInventoryGetInventoryDocumentPositionsResponseRowV3",
    "NebularApiControllersV3DocumentsInventoryGetInventoryDocumentPositionsResponseV3",
    "NebularApiControllersV3DocumentsInventoryGetInventoryDocumentResponseV3",
    "NebularApiControllersV3DocumentsManagementCreateManagementDocumentRequestPositionV3",
    "NebularApiControllersV3DocumentsManagementCreateManagementDocumentRequestV3",
    "NebularApiControllersV3DocumentsManagementGetManagementDocumentPositionsResponseRowV3",
    "NebularApiControllersV3DocumentsManagementGetManagementDocumentPositionsResponseV3",
    "NebularApiControllersV3DocumentsManagementGetManagementDocumentResponseV3",
    "NebularApiControllersV3DocumentsMovementCreateMovementDocumentRequestV3",
    "NebularApiControllersV3DocumentsMovementGetMovementDocumentPositionsResponseRowV3",
    "NebularApiControllersV3DocumentsMovementGetMovementDocumentPositionsResponseV3",
    "NebularApiControllersV3DocumentsMovementGetMovementDocumentResponseV3",
    "NebularApiControllersV3DocumentsProductionCreateProductionDocumentRequestPositionV3",
    "NebularApiControllersV3DocumentsProductionCreateProductionDocumentRequestV3",
    "NebularApiControllersV3DocumentsProductionGetProductionDocumentPositionsResponseRowV3",
    "NebularApiControllersV3DocumentsProductionGetProductionDocumentPositionsResponseV3",
    "NebularApiControllersV3DocumentsProductionGetProductionDocumentResponseV3",
    "NebularApiControllersV3DocumentsWriteOffCreateWriteOffDocumentRequestPositionV3",
    "NebularApiControllersV3DocumentsWriteOffCreateWriteOffDocumentRequestV3",
    "NebularApiControllersV3DocumentsWriteOffGetWriteOffDocumentPositionsResponseRowV3",
    "NebularApiControllersV3DocumentsWriteOffGetWriteOffDocumentPositionsResponseV3",
    "NebularApiControllersV3DocumentsWriteOffGetWriteOffDocumentResponseV3",
    "NebularApiDtosCommonOrderDto",
    "NebularApiDtosGetOrderStatusWithReceiptsContent",
    "NebularApiDtosGoodCategoryDtoV2",
    "NebularApiEnumsAddingTypeEnum",
    "NebularApiEnumsAgentTypeEnum",
    "NebularApiEnumsCashlessPaymentsEnum",
    "NebularApiEnumsDevicePaymentTypeEnum",
    "NebularApiEnumsDocTypeEnum",
    "NebularApiEnumsElectronicCheckEnum",
    "NebularApiEnumsFiscalizationStatusEnum",
    "NebularApiEnumsInputMethodEnum",
    "NebularApiEnumsMarkingTypeEnum",
    "NebularApiEnumsNoReturnEnum",
    "NebularApiEnumsPaymentMethodTypeEnum",
    "NebularApiEnumsPaymentSubjectTypeEnum",
    "NebularApiEnumsTaxationSystemInOrdersEnum",
    "NebularApiEnumsUnitCodeEnum",
    "NebularApiEnumsVATRateEnum",
    "NebularApiModelsCommonApiAcquiringDataV3",
    "NebularApiModelsCommonApiCashModeSums",
    "NebularApiModelsCommonApiCheque",
    "NebularApiModelsCommonApiCredit",
    "NebularApiModelsCommonApiCustomerInfo",
    "NebularApiModelsCommonApiDateTimeModel",
    "NebularApiModelsCommonApiDebit",
    "NebularApiModelsCommonApiErrorModel",
    "NebularApiModelsCommonApiGuidModel",
    "NebularApiModelsCommonApiIndustryAttribute",
    "NebularApiModelsCommonApiMoney",
    "NebularApiModelsCommonApiOperationalAttribute",
    "NebularApiModelsCommonApiOrderDtoContent",
    "NebularApiModelsCommonApiOrderDtoExtendedContent",
    "NebularApiModelsCommonApiOrderDtoExtendedPosition",
    "NebularApiModelsCommonApiOrderDtoPosition",
    "NebularApiModelsCommonApiQrPayTransaction",
    "NebularApiModelsCommonApiReconciliations",
    "NebularApiModelsCommonApiSpasibo",
    "NebularApiModelsCommonApiTaxes",
    "NebularApiModelsCommonApiСOunters",
    "NebularApiModelsIntegrationsAdditionalUserAttribute",
    "NebularApiModelsIntegrationsAgentInfo",
    "NebularApiModelsIntegrationsCheckCloseV3",
    "NebularApiModelsIntegrationsOrderCheckClose",
    "NebularApiModelsIntegrationsSupplierInfo",
    "NebularApiModelsLkServiceAddress",
    "NebularApiModelsLkServiceBaseShop",
    "NebularApiModelsLkServiceBindDeviceToAccountModel",
    "NebularApiModelsLkServiceBindingResponse",
    "NebularApiModelsLkServiceCashiersV2CashierDevice",
    "NebularApiModelsLkServiceCashiersV2CreateCashierResponseV2",
    "NebularApiModelsLkServiceCashiersV2GetCashierResponseV2",
    "NebularApiModelsLkServiceClient",
    "NebularApiModelsLkServiceClientExtendedV2",
    "NebularApiModelsLkServiceClientV2",
    "NebularApiModelsLkServiceCustomProperty",
    "NebularApiModelsLkServiceDeviceList",
    "NebularApiModelsLkServiceDeviceModel",
    "NebularApiModelsLkServiceExtendedGoodV2",
    "NebularApiModelsLkServiceGetGoodsCategory",
    "NebularApiModelsLkServiceGetGoodsCategoryV2",
    "NebularApiModelsLkServiceGetReceiptCashier",
    "NebularApiModelsLkServiceGetShopV2",
    "NebularApiModelsLkServiceGoodsExtendedGoodDtoV2",
    "NebularApiModelsLkServiceGoodsRows2SystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7Cec85D7Bea7798ESystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7Cec85D7Bea7798E",
    "NebularApiModelsLkServiceGoodsShopInfo",
    "NebularApiModelsLkServiceGoodsV2SetPrices",
    "NebularApiModelsLkServiceGroup",
    "NebularApiModelsLkServiceIdResponseV2",
    "NebularApiModelsLkServiceImg",
    "NebularApiModelsLkServiceLkShift",
    "NebularApiModelsLkServiceLkSlip",
    "NebularApiModelsLkServiceLoyaltyCard",
    "NebularApiModelsLkServiceModifierGood",
    "NebularApiModelsLkServiceModifierOption",
    "NebularApiModelsLkServiceOrdersV2OrdersResponse",
    "NebularApiModelsLkServiceOrdersV2PostOrderV2",
    "NebularApiModelsLkServicePostCashier",
    "NebularApiModelsLkServicePostShopV2",
    "NebularApiModelsLkServiceReceiptProperties",
    "NebularApiModelsLkServiceReceiptsV2ClientInfo",
    "NebularApiModelsLkServiceReceiptsV2LoyaltyContent",
    "NebularApiModelsLkServiceReceiptsV2ReceiptsResponseV2",
    "NebularApiModelsLkServiceReceiptsV2Row",
    "NebularApiModelsLkServiceReceiptTypeEnum",
    "NebularApiModelsLkServiceRow2SystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7Cec85D7Bea7798ESystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7Cec85D7Bea7798E",
    "NebularApiModelsLkServiceShopData",
    "NebularApiModelsLkServiceShopsShopV2SetPrices",
    "NebularApiModelsLkServiceSlotInfo",
    "NebularApiModelsLkServiceSorting",
    "NebularApiModelsLkServiceV3ContractorsV3ContractorsSortedV3",
    "NebularApiModelsLkServiceV3ContractorsV3CreateContractorRequestV3",
    "NebularApiModelsLkServiceV3ContractorsV3CreateContractorResponseV3",
    "NebularApiModelsLkServiceV3ContractorsV3GetContractorResponseV3",
    "NebularApiModelsLkServiceV3ContractorsV3ListContractorsResponseV3",
    "NebularApiModelsLkServiceV3ContractorsV3ListContractorsRowV3",
    "NebularApiModelsLkServiceV3ContractorsV3UpdateContractorRequestV3",
    "NebularApiModelsLkServiceV3DevicesV3BindDeviceToAccountModelV3",
    "NebularApiModelsLkServiceV3DevicesV3BindDeviceToAccountModelV3Cashier",
    "NebularApiModelsLkServiceV3DevicesV3BindDeviceToAccountModelV3Shop",
    "NebularApiModelsLkServiceV3DevicesV3DeviceSettingsProfileV3",
    "NebularApiModelsLkServiceV3DevicesV3DeviceSettingV3",
    "NebularApiModelsLkServiceV3DevicesV3DevicesSortedV3",
    "NebularApiModelsLkServiceV3DevicesV3DevicesV3CustomProperty",
    "NebularApiModelsLkServiceV3DevicesV3DevicesV3Shop",
    "NebularApiModelsLkServiceV3DevicesV3GetDeviceResponseV3",
    "NebularApiModelsLkServiceV3DevicesV3ListDevicesResponseV3",
    "NebularApiModelsLkServiceV3DevicesV3ListDevicesRowV3",
    "NebularApiModelsLkServiceV3DocumentsV3CreateDocumentRelatedEntityV3",
    "NebularApiModelsLkServiceV3DocumentsV3CreateDocumentRequestPositionV3",
    "NebularApiModelsLkServiceV3DocumentsV3CreateDocumentResponseV3",
    "NebularApiModelsLkServiceV3DocumentsV3DocumentPositionsResponseRowGoodV3",
    "NebularApiModelsLkServiceV3DocumentsV3DocumentsSortedV3",
    "NebularApiModelsLkServiceV3DocumentsV3GetDocumentRelatedEntityV3",
    "NebularApiModelsLkServiceV3ErrorModelV3",
    "NebularApiModelsLkServiceV3ErrorV3",
    "NebularApiModelsLkServiceWarehouseV2WarehouseGetShopV2",
    "NebularApiModelsReceiptModelsBaseClientInfo",
    "NebularApiModelsReceiptModelsBaseLoyaltyContent",
    "NebularApiModelsReceiptModelsLkRows1NebularApiModelsLkServiceLkShiftNebularApiVersion1000CultureneutralPublicKeyTokennull",
    "NebularApiModelsReceiptModelsLkRows1NebularApiModelsLkServiceLkSlipNebularApiVersion1000CultureneutralPublicKeyTokennull",
    "NebularApiModelsReceiptModelsLoyalty",
    "NebularApiModelsReceiptModelsModifierOptionPointer",
    "NebularApiModelsReceiptModelsPaymentV3",
    "NebularApiModelsReceiptModelsReceiptContentV3",
    "NebularApiModelsReceiptModelsReceiptPositionV32",
    "NebularApiModelsReceiptModelsReceiptV3",
    "PostV2ListGoodsBody",
    "PostV2ListGoodsCategoriesBody",
    "PostV2ShopsPricesBody",
)
